spring.application.name=realtime-analytics
server.port=8090
api.security.application-keys.imotion=${API_SECURITY_APPLICATION_KEY_IMOTION:nRQOlI5jF7wHc7xF2awR3RO1fMq5OiqEnGvMxvrX3pk}
druid.bootstrap.enabled=${DRUID_BOOTSTRAP_ENABLED:false}
